<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="administrator.aspx.cs" Inherits="GroupProject.administrator" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Administrator</title>
    <link href="style.css" rel="stylesheet" />
        <link rel="icon"
          type="image/png"
          href="flame.png"/>
</head>
<body>
    <form id="form1" runat="server">
       <div id="wrapper">

	        <header><h1 id="tagline"> CONQUEROR HOOK AND LADDER</h1></header>
                   <main>
                       <div id="ribbon"></div>
			            <div id="left">
				            <nav>
					            <ul>
						            <li><a href ="index.html"> HOME </a></li>
						            <li><a href="gallery.html"> GALLERY </a></li>
                                    <li><a href="volunteer.aspx"> VOLUNTEERS </a></li>
						            <li><a href="administrator.aspx"> ADMINISTRATOR </a></li>
					            </ul>
				            </nav>
		            	</div>
                       	<div id="middle">
                            <h1 id="about"> Signed-In Volunteers:</h1>
                            <div id="showResults2" runat="server"/>

                                <asp:GridView ID="AdminTable" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="ID" DataSourceID="SqlDataSource1" PageSize="20" Visible="True" >
                                    <Columns>
                                        <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" ItemStyle-Width="40px" />
                                        <asp:BoundField DataField="fname" HeaderText="First Name" SortExpression="fname" ItemStyle-Width="140px" />
                                        <asp:BoundField DataField="lname" HeaderText="Last Name" SortExpression="lname" ItemStyle-Width="140px" />
                                        <asp:BoundField DataField="phone" HeaderText="Phone" SortExpression="phone" ItemStyle-Width="140px" />
                                        <asp:BoundField DataField="email" HeaderText="E-mail" SortExpression="email" ItemStyle-Width="140px" />
                                        <asp:BoundField DataField="prefmethod" HeaderText="Preffered Method" SortExpression="prefmethod" />
                                        <asp:BoundField DataField="besttime" HeaderText="Best Time to Call" SortExpression="besttime" ItemStyle-Width="140px" />
                                    </Columns>
                                </asp:GridView>
                                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:firedep1ConnectionString %>"
                                    SelectCommand="SELECT [ID], [fname], [lname], [phone], [email], [prefmethod], [besttime] FROM [tblVolunteers]"
                                    UpdateCommand="UPDATE [tblVolunteers] Set [fname]=@fname,[lname]=@lname, [phone]=@phone, [email]=@email, [prefmethod]=@prefmethod, [besttime]=@besttime where [ID]=@ID"
                                    DeleteCommand="DELETE from [tblVolunteers] where [ID]=@ID"></asp:SqlDataSource>





                        </div>
          
                   </main>
           <footer>
            <p id="adress">1000 Avenue Of the Americas, New York, NY 10010  |  Copyright &copy; 2018 Conqueror Hook and Ladder</p><br />
		</footer>
        </div>
    </form>
</body>
</html>
